FROM node:8.16.0-alpine

RUN mkdir /app
WORKDIR /app

RUN npm install -g nodemon typescript cross-env

COPY package.json package.json
RUN npm install && mv node_modules /node_modules

COPY . .

LABEL maintainer="Varis Darasirikul"

CMD npm run build && npm run dev
