FROM node:7.7-alpine

RUN mkdir /app
WORKDIR /app

RUN npm install -g nodemon typescript

COPY package.json package.json
RUN npm install && mv node_modules /node_modules

COPY . .
RUN tsc

LABEL maintainer="Varis Darasirikul"

CMD npm run dev
